### Python Numpy 

In [26]:
import numpy as np

##### Ways of creating numpy array

In [27]:
# Method 1: Via list
a = [1, 2, 4, 5]
np.array(a)

array([1, 2, 4, 5])

In [28]:
b = [[1, 2, 3], [1, 3, 4], [2, 34, 32], [2, 34, 3]]
np.array(b)

array([[ 1,  2,  3],
       [ 1,  3,  4],
       [ 2, 34, 32],
       [ 2, 34,  3]])

In [29]:
# Method 2: via np.arange

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(5, 15, 3)

array([ 5,  8, 11, 14])

In [31]:
# Method 3: Via np.zeros

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.zeros((10,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [33]:
# Method 4: Via np.ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [34]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
# Method 5: Via np.linspace

np.linspace(0,2,100)

array([0.        , 0.02020202, 0.04040404, 0.06060606, 0.08080808,
       0.1010101 , 0.12121212, 0.14141414, 0.16161616, 0.18181818,
       0.2020202 , 0.22222222, 0.24242424, 0.26262626, 0.28282828,
       0.3030303 , 0.32323232, 0.34343434, 0.36363636, 0.38383838,
       0.4040404 , 0.42424242, 0.44444444, 0.46464646, 0.48484848,
       0.50505051, 0.52525253, 0.54545455, 0.56565657, 0.58585859,
       0.60606061, 0.62626263, 0.64646465, 0.66666667, 0.68686869,
       0.70707071, 0.72727273, 0.74747475, 0.76767677, 0.78787879,
       0.80808081, 0.82828283, 0.84848485, 0.86868687, 0.88888889,
       0.90909091, 0.92929293, 0.94949495, 0.96969697, 0.98989899,
       1.01010101, 1.03030303, 1.05050505, 1.07070707, 1.09090909,
       1.11111111, 1.13131313, 1.15151515, 1.17171717, 1.19191919,
       1.21212121, 1.23232323, 1.25252525, 1.27272727, 1.29292929,
       1.31313131, 1.33333333, 1.35353535, 1.37373737, 1.39393939,
       1.41414141, 1.43434343, 1.45454545, 1.47474747, 1.49494

In [36]:
# Method 6: Via np.eye, it creats identity matrix

np.eye(4) # only takes single parameter; as it needs to be of square shape

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
# Method 7: via np.random.rand / np.random.randn /np.random.int

np.random.rand(4)

array([0.24073022, 0.36518972, 0.86514682, 0.42540167])

In [38]:
np.random.rand(4,5)

array([[0.51490499, 0.38408879, 0.21634805, 0.53098245, 0.77518204],
       [0.73247056, 0.46461882, 0.50993627, 0.04397247, 0.65327528],
       [0.358115  , 0.40132506, 0.26745664, 0.92254828, 0.33423355],
       [0.08268859, 0.87327069, 0.03350519, 0.53371939, 0.92420316]])

In [39]:
np.random.randn(4)

array([-0.06601732,  0.6833044 , -0.33956261,  1.25754478])

In [40]:
np.random.randn(4,5)

array([[-0.15873241,  0.90930534, -0.17774695, -0.53298075, -0.51976913],
       [ 0.37170662, -1.26756964, -0.12977635, -1.81486015,  0.52248478],
       [-0.65153521,  0.58100492,  1.77136086,  0.32916364, -1.93917701],
       [-2.08307322,  1.24230336, -0.2792623 , -1.12744947, -0.77368306]])

In [41]:
np.random.randint(1, 100, 12) # find 12 random numbers between 1->100 

array([44, 54, 28, 49, 24, 52, 96, 39, 57, 75, 33, 35])

##### Reshaping an array

In [53]:
arr = np.random.randn(4)

In [54]:
arr.reshape(2, 2)

array([[ 0.21909869, -0.37329254],
       [-1.19238415, -0.17712916]])

##### Operations on array

In [55]:
# Find maximum
arr.max()

0.21909869487361952

In [56]:
# Find minimum
arr.min()

-1.192384149907251

In [57]:
# position of maximum value
arr.argmax()

0

In [58]:
# position of min value
arr.argmin()

2

In [59]:
# find data type of elements in array
arr.dtype

dtype('float64')

##### Numpy indexing and selection

In [61]:
arr = np.arange(0, 11)               

In [62]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
# get single value
arr[8]

8

In [64]:
arr[:4]

array([0, 1, 2, 3])

In [66]:
arr[1:4]

array([1, 2, 3])

In [67]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
# the slice of numpy array, is actual reference to array
# see the example below

arr_two = np.arange(0, 20, 3)

In [69]:
arr_two

array([ 0,  3,  6,  9, 12, 15, 18])

In [70]:
slice_arr = arr_two[:3]

In [72]:
slice_arr[:] = 88

In [73]:
slice_arr

array([88, 88, 88])

In [74]:
arr_two

array([88, 88, 88,  9, 12, 15, 18])

In [75]:
# to avoid this you could use copy

arr_coppy = arr_two[:3].copy()

In [76]:
arr_coppy

array([88, 88, 88])

In [77]:
arr_coppy[:2] = 2

In [78]:
arr_two

array([88, 88, 88,  9, 12, 15, 18])